train:
  experiment_id: null
  epochs: 200
  lr: 8e-4
  pretrained: True
  early_stop_thresh: 10
  loss_function: "seesaw"
  batch_size: 128
  num_dataloader_workers: 16
  image_resize: 224
  validation_frac: 0.1
  max_norm: 1.0
  undersample: False
  oversample: False
  equal_undersampled_val: True
  oversample_prop: 0.1
  dropout_rate: 0.5
  weight_decay: 1e-5
  balanced_sampler: False
  use_lr_finder: False
  fine_tune_after_n_epochs: 4
  skip_frozen_epochs_load_failed_model: False
  notes: model is efficientnet_b0 with imagenet weights and autoaug augmentations
open-set-recognition:
  embedder_experiment_id: null
  embedder_layer_offset: -2
  dlr: 1e-5
  glr: 1e-5
  batch_size: 128
  n_workers: 16
  openset_embeddings_name: null  # TODO: derive this from embedder_experiment_id
  closedset_embeddings_name: null  # TODO: derive this from embedder_experiment_id
  image_size: 224
