# reference: https://hydra.cc/docs/tutorials/basic/your_first_app/using_config/
train:
  experiment_id: null
  model_id: "efficientnet_b0"
  use_timm: False
  epochs: 200
  lr: 1.44e-2  # found with lr finder
  use_lr_finder: False
  pretrained: True
  early_stop_thresh: 10
  loss_function: "seesaw"
  use_poison_loss: True  # check me
  include_unknowns: True  # check me
  batch_size: 128
  num_dataloader_workers: 16
  worker_timeout_s: 180
  image_resize: 224
  validation_frac: 0.1
  max_norm: 1.0
  undersample: False
  oversample: False
  equal_undersampled_val: True
  oversample_prop: 0.1
  dropout_rate: 0.5
  weight_decay: 1e-5
  balanced_sampler: False
  fine_tune_after_n_epochs: 4
  skip_frozen_epochs_load_failed_model: False  # check me
  notes: model is efficientnet_b0 with imagenet weights and trivialaug  # check me
  n_classes: 1604
  lr_scheduler: "reducelronplateau"
  lr_scheduler_patience: 4
open-set-recognition:
  embedder_experiment_id: "seesaw_04_02_2024"
  embedder_layer_offset: -1
  dlr: 1e-5
  glr: 1e-5
  batch_size: 128
  n_workers: 16
  openset_embeddings_name: "openset_embeddings_${open-set-recognition.embedder_experiment_id}.h5"
  closedset_embeddings_name: "closedset_embeddings_${open-set-recognition.embedder_experiment_id}.h5"
  image_size: 224
  pretrained: True
  openset_n_train: 2000
  openset_n_val: 200
  closedset_n_train: 50000
  embedding_size: 1280
evaluate:
  experiment_id: "2024-04-16 unknown fine tune"
  model_id: "efficientnet_b0"
  use_timm: False
unknown-fine-tune:
  experiment_id: "seesaw_04_02_2024"
  epochs: 200
  lr: 8e-5
  batch_size: 128
  early_stop_thresh: 10
  loss_function: "seesaw"
  use_lr_finder: False
  lr_scheduler: "reducelronplateau"
  lr_scheduler_patience: 4
